const products = [
    { img: './product_photo/NETAC TM-21.png', title: 'NETAC TM-21 — <br><b>Сенсорный монитор</b>', full_title: 'NETAC TM-21 - <b>сенсорный монитор 21.5</b>', full_desc: 'NETAC TM-21 - <b>сенсорный монитор 21.5</b>', desc: `• IPS Full HD, 10 касаний<br>• USB-хаб, HDMI/VGA, динамики<br>• для касс, Digital-Signage, терминалов<br>• POS-ПО, интерактивные витрины<br>` },
    { img: './product_photo/NETAC NB-300_улучшен.png', title: 'NETAC NB-300 <br><b>Компактная и мощная портативная электростанция</b>', full_title: 'NETAC NB-300', full_desc: 'NETAC TM-21 - <b>сенсорный монитор 21.5</b>', desc: `• IPS Full HD, 10 касаний<br>• USB-хаб, HDMI/VGA, динамики<br>• для касс, Digital-Signage, терминалов<br>• POS-ПО, интерактивные витрины<br>` },
    { img: 'product_photo/высокий 3.png', title: 'PP 606 <br><b>Терминал самообслуживания для ПВЗ</b>', full_title: 'PP 303', full_desc: 'NETAC TM-21 - <b>сенсорный монитор 21.5</b>', desc: `• IPS Full HD, 10 касаний<br>• USB-хаб, HDMI/VGA, динамики<br>• для касс, Digital-Signage, терминалов<br>• POS-ПО, интерактивные витрины<br>` },
    { img: './product_photo/высокий 1_улучшен.png', title: 'NETAC NB-300', full_title: 'NETAC NB-300', full_desc: 'NETAC TM-21 - <b>сенсорный монитор 21.5</b>', desc: `• IPS Full HD, 10 касаний<br>• USB-хаб, HDMI/VGA, динамики<br>• для касс, Digital-Signage, терминалов<br>• POS-ПО, интерактивные витрины<br>` },
    { img: '/product_photo/высокий 3.png', title: 'PP 303', full_title: 'PP 303', full_desc: 'NETAC TM-21 - <b>сенсорный монитор 21.5</b>', desc: `• IPS Full HD, 10 касаний<br>• USB-хаб, HDMI/VGA, динамики<br>• для касс, Digital-Signage, терминалов<br>• POS-ПО, интерактивные витрины<br>` },
    { img: './product_photo/NETAC TM-21.png', title: 'AAAAA', full_title: 'NETAC TM-21 - <b>сенсорный монитор 21.5</b>', full_desc: 'NETAC TM-21 - <b>сенсорный монитор 21.5</b>', desc: `• IPS Full HD, 10 касаний<br>• USB-хаб, HDMI/VGA, динамики<br>• для касс, Digital-Signage, терминалов<br>• POS-ПО, интерактивные витрины<br>` },
    { img: './product_photo/NETAC NB-300_улучшен.png', title: 'NETAC NB-300', full_title: 'NETAC NB-300', full_desc: 'NETAC NB-300 - <b>портативная электростанция</b>', desc: `• IPS Full HD, 10 касаний<br>• USB-хаб, HDMI/VGA, динамики<br>• для касс, Digital-Signage, терминалов<br>• POS-ПО, интерактивные витрины<br>` },
    { img: 'product_photo/высокий 3.png', title: 'PP 303', full_title: 'PP 303', full_desc: 'NETAC TM-21 - <b>сенсорный монитор 21.5</b>', desc: `• IPS Full HD, 10 касаний<br> • USB-хаб, HDMI/VGA, динамики<br> • для касс, Digital-Signage, терминалов<br> • POS-ПО, интерактивные витрины` },
    { img: './product_photo/NETAC NB-300_улучшен.png', title: 'NETAC NB-300', full_title: 'NETAC NB-300', full_desc: 'NETAC TM-21 - <b>сенсорный монитор 21.5</b>', desc: `• IPS Full HD, 10 касаний<br>• USB-хаб, HDMI/VGA, динамики<br>• для касс, Digital-Signage, терминалов<br>• POS-ПО, интерактивные витрины<br>` },
    { img: '/product_photo/высокий 3.png', title: 'PP 303', full_title: 'PP 303', full_desc: 'NETAC TM-21 - <b>сенсорный монитор 21.5</b>', desc: 'Мини-терминал самообслуживания для ПВЗ' },
    { img: '/product_photo/высокий 3.png', title: 'PP 303', full_title: 'PP 303', full_desc: 'NETAC TM-21 - <b>сенсорный монитор 21.5</b>', desc: 'Мини-терминал самообслуживания для ПВЗ' }
];

export default products;